"""Usuarios

Revision ID: 058845e70948
Revises: ade3d17e7c7a
Create Date: 2024-01-13 16:45:58.303148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '058845e70948'
down_revision = 'ade3d17e7c7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('pwdhash', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
